### ISSUE TITLE
isitdtuctf2024/mixer2

### ISSUE THREAD

**Issue by x-64** [pwncollege/ctf-archive#36]
The chall.py have CRLF (\r\n) line endings, which break the shebang and the assert flag < p fails since flag has more than 256 bits.

**Comment by prathamgupta36** [comment]
It should be fixed now.

**Comment by x-64** [comment]
The assert still fails:

hacker@isitdtuctf2024~crypto-100-share-mixer-2:~$ /challenge/chall.py 
Traceback (most recent call last):
  File "/challenge/chall.py", line 8, in <module>
    assert flag < p
AssertionError

**Comment by prathamgupta36** [comment]
This should fix it, I tried my script and got the flag as well.

**Comment by x-64** [comment]
Let me come back to this challenge. As far as I understand it's only possible to find the flag if p is bigger than flag as working with mod p prevents lager values than p for flag. I have tested and found the following code working. Please consider updating Mixer 1 and 2.

flag = bytes_to_long(open("/flag", "rb").read().strip())
p = getPrime(flag.bit_length()+1)
assert flag < p

**Comment by prathamgupta36** [comment]
does the code we have right now not work? I do get the point you are making and the `code snippet` you shared should work as well and I don't mind changing if the current code has problems

**Comment by prathamgupta36** [comment]
I ran my code and found that the change you suggested made getting the `flag` 4 times faster, let me know if thats was the main goal of your suggestion

**Comment by x-64** [comment]
My point is that I can reconstruct flags up to 32 characters (256 bit) but no longer ones. As the flags in pwn.college are longer, I canot reconstruct the actual flag.

**Comment by prathamgupta36** [comment]
I understand, I was using the `practice` flag but I ran it with the regular `pwn.college` flag and your method works. Thanks for the suggestion!

**Comment by x-64** [comment]
Thank you! 
Works now.
